
function abbreviations
  if status --is-interactive
      abbr --add --global en 'echo -n'
      abbr --add --global ee 'echo -e'
      abbr --add --global w 'watch -n 1'
      abbr --add --global n 'netstat -tlpn'
      abbr --add --global t 'tmux'
      abbr --add --global ta 'tmux a'
      abbr --add --global gc 'git clone'
      abbr --add --global ga 'git add -A'
      abbr --add --global gco 'git commit -m'
      abbr --add --global gca 'git commit -am'
      abbr --add --global gp 'git push'
      abbr --add --global gpf 'git push -f'
      abbr --add --global gpu 'git push -u origin main'
      abbr --add --global gpl 'git pull'
      abbr --add --global gf 'git fetch'
      abbr --add --global gfo 'git fetch origin'
      abbr --add --global gr 'git remote -v'
      abbr --add --global grao 'git remote add origin'
      abbr --add --global grro 'git remote remove origin'
      abbr --add --global gs 'git status'
      abbr --add --global gl 'git log'
      abbr --add --global gd 'git diff'
      abbr --add --global y 'yarn'
      abbr --add --global yi 'yarn init'
      abbr --add --global yr 'yarn run'
      abbr --add --global yd 'yarn dev'
      abbr --add --global ya 'yarn add -D'
      abbr --add --global yga 'yarn global add'
      abbr --add --global ygu 'yarn global upgrade'
      abbr --add --global yb 'yarn build'
      abbr --add --global yp 'yarn preview'
      abbr --add --global yf 'yarn format'
      abbr --add --global yl 'yarn lint'
      abbr --add --global d 'docker'
      abbr --add --global dp 'docker ps'
      abbr --add --global dpa 'docker ps -a'
      abbr --add --global dpull 'docker pull'
      abbr --add --global dpush 'docker push'
      abbr --add --global dr 'docker run --rm -it'
      abbr --add --global dst 'docker start'
      abbr --add --global dsp 'docker stop'
      abbr --add --global db 'docker build'
      abbr --add --global di 'docker images'
      abbr --add --global de 'docker exec'
      abbr --add --global da 'docker attach'
      abbr --add --global dl 'docker logs'
      abbr --add --global dlf 'docker logs -f'
      abbr --add --global drm 'docker container rm'
      abbr --add --global dirm 'docker image rm'
      abbr --add --global dc 'docker compose'
      abbr --add --global dcu 'docker compose up'
      abbr --add --global dcud 'docker compose up -d'
      abbr --add --global dcd 'docker compose down'
      abbr --add --global dcdv 'docker compose down -v'
      abbr --add --global dcp 'docker compose ps'
      abbr --add --global dcpa 'docker compose ps -a'
      abbr --add --global dcst 'docker compose start'
      abbr --add --global dcsp 'docker compose stop'
      abbr --add --global dcr 'docker compose restart'
      abbr --add --global dce 'docker compose exec'
      abbr --add --global dcl 'docker compose logs'
      abbr --add --global dclf 'docker compose logs -f'
      abbr --add --global dcrm 'docker compose rm'
      abbr --add --global np 'npm'
      abbr --add --global npi 'npm install'
      abbr --add --global npci 'npm ci'
      abbr --add --global npa 'npm install --save-dev'
      abbr --add --global npg 'npm install -g'
      abbr --add --global npun 'npm uninstall'
      abbr --add --global npr 'npm run'
      abbr --add --global npd 'npm run dev'
      abbr --add --global nps 'npm start'
      abbr --add --global npb 'npm run build'
      abbr --add --global npp 'npm run preview'
      abbr --add --global npf 'npm run format'
      abbr --add --global npl 'npm run lint'
      abbr --add --global npt 'npm test'
      abbr --add --global npin 'npm init'
      abbr --add --global npo 'npm outdated'
      abbr --add --global npu 'npm update'
      abbr --add --global nppb 'npm publish'
      abbr --add --global npls 'npm list'
      abbr --add --global npx 'npx'
  end
end
