
function abbreviations
  if status --is-interactive
      abbr --add --global en 'echo -n'
      abbr --add --global ee 'echo -e'
      abbr --add --global w 'watch -n 1'
      abbr --add --global n 'netstat -tlpn'
      abbr --add --global t 'tmux attach-session 2>/dev/null || tmux new-session'
      abbr --add --global gc 'git clone'
      abbr --add --global ga 'git add -A'
      abbr --add --global gco 'git commit -m'
      abbr --add --global gca 'git commit -am'
      abbr --add --global gp 'git push'
      abbr --add --global gpf 'git push -f'
      abbr --add --global gpu 'git push -u origin main'
      abbr --add --global gpl 'git pull'
      abbr --add --global gf 'git fetch'
      abbr --add --global gfo 'git fetch origin'
      abbr --add --global gr 'git remote -v'
      abbr --add --global grao 'git remote add origin'
      abbr --add --global grro 'git remote remove origin'
      abbr --add --global gs 'git status'
      abbr --add --global gl 'git log'
      abbr --add --global gd 'git diff'
      abbr --add --global y 'yarn'
      abbr --add --global yi 'yarn init'
      abbr --add --global yr 'yarn run'
      abbr --add --global yd 'yarn dev'
  end
end
